spring:
  datasource:
    hikari:
      #rewriteBatchedStatements=true 는 bulk insert 를 사용하기 위한 옵션
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?rewriteBatchedStatements=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: never