spring:
  batch:
    job:
      names: ${job.name:NONE}

#      initialize-schema:  # 스크립트 생성 시점을 설정한다.
  datasource:
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations: classpath:person.sql
#  datasource:
#    hikari:
#      driver-class-name: org.h2.Driver
#    sql:
#      init:
#        data-locations: classpath:person.sql

#datasource:
#  hikari:
#    jdbc-url: jdbc:h2://localhost:3306/spring_batch
#    driver-class-name: org.h2.Driver
#    username: root
#    password:



















#server:
#  port: 9090
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password:
